"""add verification fields

Revision ID: 68298d73f726
Revises: 
Create Date: 2026-05-27 04:01:36.362052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68298d73f726'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('university_domain', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_attempts', sa.Integer(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_attempts')
        batch_op.drop_column('email_verification_expires_at')
        batch_op.drop_column('email_verification_code')
        batch_op.drop_column('university_domain')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
