"""Add deletion_pending_until

Revision ID: b1134cd8e355
Revises: a3f5b7c2d9e0
Create Date: 2026-06-09 16:09:15.729050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1134cd8e355'
down_revision = 'a3f5b7c2d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('kg_saved',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=True)
        batch_op.alter_column('pin_code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletion_pending_until', sa.DateTime(), nullable=True))
        batch_op.alter_column('kg_saved_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('kg_saved_total',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('deletion_pending_until')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('pin_code',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
        batch_op.alter_column('kg_saved',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
