"""refactor_pin_fields

Revision ID: cb6cf413e00d
Revises: ec4614c2789b
Create Date: 2026-06-27 20:53:51.059074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6cf413e00d'
down_revision = 'ec4614c2789b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE items SET pin_code = NULL WHERE LENGTH(pin_code) > 4"))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('pin_code',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.drop_column('pin_plaintext')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_plaintext', sa.VARCHAR(length=4), nullable=True))
        batch_op.alter_column('pin_code',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
