"""add short_name column

Revision ID: e90c2a184876
Revises: f01e828249ea
Create Date: 2026-07-11 16:59:44.837789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90c2a184876'
down_revision = 'f01e828249ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_configs', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
