"""Add leaderboard and university config tables and columns

Revision ID: f01e828249ea
Revises: fad26b8ec8b7
Create Date: 2026-07-09 14:08:44.330931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01e828249ea'
down_revision = 'fad26b8ec8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('subdomain_slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email_domain', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('brand_color', sa.String(length=7), nullable=False),
    sa.Column('brand_text_color', sa.String(length=7), nullable=False),
    sa.Column('autumn_term_start', sa.DateTime(), nullable=True),
    sa.Column('autumn_term_end', sa.DateTime(), nullable=True),
    sa.Column('spring_term_start', sa.DateTime(), nullable=True),
    sa.Column('spring_term_end', sa.DateTime(), nullable=True),
    sa.Column('summer_term_start', sa.DateTime(), nullable=True),
    sa.Column('summer_term_end', sa.DateTime(), nullable=True),
    sa.Column('logo_status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('university_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_university_configs_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_university_configs_subdomain_slug'), ['subdomain_slug'], unique=True)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_domain', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['university_domain'], ['university_configs.domain'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_university_domain'), ['university_domain'], unique=False)

    op.create_table('weekly_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_domain', sa.String(length=100), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('kg_saved', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['university_domain'], ['university_configs.domain'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_domain', 'week_start', 'rank', name='uq_weekly_snapshot_rank')
    )
    with op.batch_alter_table('weekly_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_weekly_snapshot_domain_week', ['university_domain', 'week_start'], unique=False)

    op.create_table('seasonal_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('university_domain', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('kg_saved', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['university_domain'], ['university_configs.domain'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'rank', name='uq_seasonal_snapshot_rank')
    )
    with op.batch_alter_table('seasonal_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_seasonal_snapshot_domain', ['university_domain'], unique=False)

    with op.batch_alter_table('university_logos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_university_logos_domain'))

    op.drop_table('university_logos')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on_leaderboard', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))

    from sqlalchemy.sql import table, column
    uni_configs = table(
        'university_configs',
        column('domain', sa.String),
        column('subdomain_slug', sa.String),
        column('display_name', sa.String),
        column('email_domain', sa.String),
        column('timezone', sa.String),
        column('brand_color', sa.String),
        column('brand_text_color', sa.String),
        column('logo_status', sa.String),
    )

    op.bulk_insert(uni_configs, [
        {
            'domain': 'brookes.ac.uk',
            'subdomain_slug': 'brookes',
            'display_name': 'Oxford Brookes University',
            'email_domain': 'brookes.ac.uk',
            'timezone': 'Europe/London',
            'brand_color': '#002855',
            'brand_text_color': '#ffffff',
            'logo_status': 'pending',
        },
        {
            'domain': 'ox.ac.uk',
            'subdomain_slug': 'ox',
            'display_name': 'Oxford University',
            'email_domain': 'ox.ac.uk',
            'timezone': 'Europe/London',
            'brand_color': '#002147',
            'brand_text_color': '#ffffff',
            'logo_status': 'pending',
        },
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_on_leaderboard')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('sold_at')

    op.create_table('university_logos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), nullable=False),
    sa.Column('logo_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('university_logos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_university_logos_domain'), ['domain'], unique=1)

    with op.batch_alter_table('seasonal_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_seasonal_snapshot_domain')

    op.drop_table('seasonal_snapshots')
    with op.batch_alter_table('weekly_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_weekly_snapshot_domain_week')

    op.drop_table('weekly_snapshots')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_university_domain'))

    op.drop_table('seasons')
    with op.batch_alter_table('university_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_university_configs_subdomain_slug'))
        batch_op.drop_index(batch_op.f('ix_university_configs_domain'))

    op.drop_table('university_configs')
    # ### end Alembic commands ###
