"""Add university logo model

Revision ID: fad26b8ec8b7
Revises: cb6cf413e00d
Create Date: 2026-07-04 14:43:33.397137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad26b8ec8b7'
down_revision = 'cb6cf413e00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university_logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('logo_status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('university_logos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_university_logos_domain'), ['domain'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_logos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_university_logos_domain'))

    op.drop_table('university_logos')
    # ### end Alembic commands ###
