"""Add cancellation records

Revision ID: feddbe5c7f51
Revises: 68298d73f726
Create Date: 2026-06-03 12:52:06.316651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feddbe5c7f51'
down_revision = '68298d73f726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=False),
    sa.Column('other_party_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=False),
    sa.Column('hours_held', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('cancelled_by_role', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['other_party_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancellation_records')
    # ### end Alembic commands ###
